### ISSUE TITLE
'CustomCrops' Plugin Fails to Enable Due to Missing AdvancedSeasonsAPI Class

### ISSUE THREAD

**Issue by var1nthon** [Xiao-MoMi/Custom-Crops#35]
**Describe the bug**
The 'CustomCrops' plugin fails to enable on server startup, throwing a 'java.lang.NoClassDefFoundError' related to the 'AdvancedSeasonsAPI'

**To Reproduce**
1. Start the Minecraft server with the CustomCrops and AdvancedSeasons plugins installed.
2. Observe the server console logs during startup.
3. Notice the error when the CustomCrops plugin attempts to enable.

**Expected behavior**
The 'CustomCrops' plugin should enable without errors, properly integrating with the 'AdvancedSeasons' plugin.

**Error**
Error log: https://paste.helpch.at/yaqamaluqe.css
Latest log: https://paste.helpch.at/qeyizacawi.makefile

**Versions used**
CustomCrops version: v3.5.7.5
AdvancedSeasons version: 1.4.1
Minecraft version: 1.21
Paper version: 1.21-124-master@df3b654
Java version: 22

**Relevant plugins**
PlaceholderAPI v2.11.6
Oraxen v1.179.0
WorldGuard v7.0.11-beta1+a801a9d
LuckPerms v5.4.134
CMI v9.7.4.9

**Comment by Xiao-MoMi** [comment]
Seems that AdvancedSeasons has updated their API but sadly that I don't have a jar for test. Contact me on Discord with further fix and test.

**Comment by Xiao-MoMi** [comment]
Fixed in next release
