### ISSUE TITLE
1.20.2使用洒水器会直接在屏幕输出韩文而不是对应替换的贴图

### ISSUE THREAD

**Issue by jimi1104** [Xiao-MoMi/Custom-Crops#37]
![2024-08-31_01 27 19](https://github.com/user-attachments/assets/299e5190-57e1-4293-8cf3-79fc055824a2)
%img_TAB%是我用来测试的贴图

**Comment by Xiao-MoMi** [comment]
大概是受到了其他插件的改包影响，非CustomCrops自身问题
