### ISSUE TITLE
Dependencies problem

### ISSUE THREAD

**Issue by iGabyTM** [Xiao-MoMi/Custom-Crops#8]
Hey, I've made a fork of the plugin to add some changes for our server but looks like some dependencies are missing. For instance I can not find an _old_ beton quest jar that has all the classes used in `OldBetonQuestCCQuest`, I've downloaded many versions but I couldn't find one that's working. Would be possible to add the dependencies in build.gradle or at least provide me with a list of versions used?

**Comment by Xiao-MoMi** [comment]
betonquest 1.12.10 and 2.0-DEV
